README.md
=> fix-docs-3

sonarqube/projects.py
sonar-audit is slow when there are a lot of groups
=> deal-with-many-groups-and-users

README.md, sonarqube/utilities.py
Improve docs and fix cmd lines help
=> honor-env-vars

README.md
=> Fixes #164

sonarqube/measures.py, sonarqube/measures_export.py, sonarqube/version.py
=> Bug fix branch metrics calculation

run_linters.sh, sonarqube/issues.py, sonarqube/issues_sync.py
=> Fix-issue-sync

deploy.sh, sonar/platform.py, sonar/sif.py, sonar/version.py, tools/audit.py
Adjust to the new system info JSON format introduced in SonarQube 9.7
Fixes #861 and #854
=> SonarQube 9.7 compatibility

sonar/projects/projects.py, sonar/version.py
=> Fix housekeeper branch verification

sonar/findings/issues.py, sonar/measures.py, sonar/projects/projects.py
=> Fix JSON loading errors - Fixes #892

sonar/projects/branches.py, tools/housekeeper.py
Fixes #890
- Can't delete a main branch
- Can't delete a non existing branch
=> Fixes branch deletion bugs

sonar/applications.py, sonar/languages.py, sonar/portfolios.py, sonar/projects/projects.py, sonar/qualityprofiles.py
=> List optional cache

sonar/platform.py, sonar/projects/projects.py, test/it.sh, test/sonar-env.sh
=> findings-export-without-sys-admin-permission

sonar/groups.py, sonar/platform.py, sonar/qualitygates.py, tools/findings_sync.py
=> Fixes #911

doc/what-is-new.md, sonar/projects/projects.py
=> Fixes #925 and #926

tools/findings_sync.py
=> Fixes #918

sonar/qualitygates.py, sonar/qualityprofiles.py
=> Restore default quality profiles and quality gates on config import

.github/workflows/build.yml
=> Fixes pipeline uses deprecated actions #954

sonar/rules.py
=> Fixes #953 - New SQ 10 rule taxonomy

sonar/platform.py, sonar/projects/projects.py, sonar/rules.py, sonar/users.py
=> Fixes sonar-audit should verify that SQ is on new 9.9 LTS or LATEST

sonar/portfolios.py, sonar/projects/projects.py, tools/findings_export.py, tools/measures_export.py
=> Fixes sonar-findings-export -b (to export branch issues) crashes #977

sonar/sif.py
=> Fixes sonar-audit does not always find edition in SIF #982

sonar/settings.py
=> Fixes #1012 Fixes #1013

sonar/settings.py, sonar/utilities.py, tools/audit.py, tools/config.py, tools/cust_measures.py, tools/findings_export.py, tools/findings_sync.py, tools/housekeeper.py, tools/loc.py, tools/measures_export.py, tools/projects_export.py, tools/projects_import.py, tools/rules_cli.py, tools/support.py
=> Occasionally check latest sonar-tool version

sonar/platform.py, sonar/projects/projects.py
=> Null webhooks fix

sonar/qualityprofiles.py
=> Rules disabled in inherited QP

tools/findings_export.py
=> Fixes Make sonar-findings-export compatible with SonarCloud

sonar/tasks.py, tools/measures_export.py
=> Remove QG details from measures export

run_linters.sh, sonar-project.properties
=> Fixes #1068

doc/sonar-audit.md, sonar/audit/rules.json, sonar/audit/rules.py, sonar/audit/sonar-audit.properties, sonar/platform.py
=> audit logs for errors or warnings

sonar/measures.py, sonar/projects/projects.py, tools/findings_export.py, tools/loc.py, tools/measures_export.py
=> skip export for projects with no access

test/it.sh, tools/measures_export.py
=> Export measures history as table

sonar/metrics.py
=> Fixes #1098

sonar/applications.py, sonar/portfolios.py, sonar/settings.py
=> Fixes #1175

doc/what-is-new.md, sonar/app_branches.py, sonar/applications.py, sonar/projects.py
=> Fixes #1193

cli/audit.py, cli/config.py, cli/cust_measures.py, cli/findings_export.py, cli/findings_sync.py, cli/housekeeper.py, cli/loc.py, cli/measures_export.py, cli/options.py, cli/projects_export.py, cli/projects_import.py, cli/rules_cli.py, doc/what-is-new.md, sonar/errcodes.py, sonar/exceptions.py, sonar/platform.py, sonar/qualitygates.py
=> Fix usage with SonarCloud

sonar/platform.py
=> Add SonarQube URL in sonar-config export

sonar/groups.py, sonar/sqobject.py, sonar/users.py
=> Remove calls to deprecated user and group APIs

README.md, cli/audit.py, cli/config.py, cli/findings_export.py, cli/loc.py, cli/measures_export.py, cli/options.py, cli/projects_cli.py, cli/projects_export.py, cli/projects_import.py, cli/rules_cli.py, setup.py, sonar-tools, test/test_audit.py, test/test_config.py, test/test_findings.py, test/test_findings_sync.py, test/test_loc.py, test/test_logging.py, test/test_measures.py, test/test_project_export.py, test/test_rules.py, test/test_sif.py
=> More consistent projects export/import CLI

sonar/issues.py, sonar/sqobject.py
=> Gracefully handle HTTP errors in threads

sonar/permissions/permission_templates.py
=> Fixes #1287

sonar/branches.py, sonar/hotspots.py, sonar/issues.py, sonar/projects.py, sonar/utilities.py, test/test_migration.py
=> Export hotspots counts in sonar-migration

cli/findings_export.py, sonar/permissions/permission_templates.py, sonar/qualityprofiles.py, sonar/rules.py, sonar/sqobject.py, sonar/tasks.py, sonar/utilities.py
=> Fix sonar-audit bugs

cli/audit.py, sonar/projects.py
=> Fixes #1395

cli/audit.py, cli/config.py, cli/cust_measures.py, cli/findings_export.py, cli/findings_sync.py, cli/housekeeper.py, cli/loc.py, cli/measures_export.py, cli/projects_cli.py, cli/rules_cli.py, migration/migration.py
=> Own UA for each tool

setup.py
=> Fix Python 3.8 dependency

sonar/findings.py, sonar/languages.py, sonar/rules.py
=> Clean impacts implementation in findings-export

sonar/rules.py
=> Guess lang of external rules when missing

cli/measures_export.py, sonar/metrics.py
=> Fix random order of metrics when using -m _all

doc/sonar-audit.md, sonar/branches.py, sonar/components.py, sonar/tasks.py
=> Audit analysis warnings on branches #776

cli/audit.py, sonar/branches.py, sonar/platform.py, sonar/portfolios.py, sonar/projects.py, sonar/qualitygates.py, sonar/settings.py, sonar/utilities.py, test/test_config.py, test/utilities.py
=> sonar-config import hardening

sonar/rules.py
=> Fix speed of SC/SQ rule/QP export

cli/rules_cli.py, sonar/platform.py, sonar/rules.py
=> MQR rules and legacy severity

sonar/app_branches.py, sonar/applications.py, sonar/branches.py, sonar/platform.py, sonar/portfolios.py, sonar/qualitygates.py
=> Fixes #1222

conf/build.sh, conf/release.sh
=> Fixes #1483

sonar/applications.py
fix #1528 for a typo in the Application.API
=> fix: application update key typo #1528

conf/run_tests.sh
=> Add condition coverage

sonar/platform.py, sonar/projects.py, sonar/settings.py
=> Fixes #1542

cli/config.py, cli/options.py, sonar/utilities.py
=> Hide tokens from all logs

cli/projects_cli.py
=> Fixes #1570

README.md
=> Fixes #1561

README.md
=> Compatibility SonarQube Server 2025.1

sonar/settings.py
=> Fixes #1579

sonar/sif_node.py
=> Proper check on JRE version

sonar/devops.py
=> Fixes #1604

sonar/app_branches.py
=> Fixes #1662

sonar/platform.py
=> Fixes #1667

sonar/hotspots.py, sonar/issues.py
=> Add comment with SQC transition is not possible

sonar/platform.py
=> Update LTA and LATEST in audits

sonar/findings.py
=> Changelog collection robust to HTTP errors

sonar/projects.py
=> Honor threads in projects zip export (search part)

cli/projects_cli.py, sonar/projects.py, sonar/tasks.py
=> Multithread import and provide feedback on import results

sonar/projects.py
=> Detect conflict in zip file names during export

sonar/hotspots.py
=> Fixes #1750

cli/measures_export.py
=> Fixes #1764

README.md, test/unit/utilities.py
=> Fixes #1785

sonar/users.py
=> Multithread user audit

sonar/projects.py, sonar/settings.py
=> Fixes #1825

sonar/audit/rules.json, sonar/qualitygates.py
=> Fixes #1845

sonar/projects.py
=> Fixes #1850

sonar/applications.py, sonar/portfolios.py
=> Fixes #1833

conf/prep_all_tests.sh, doc/sonar-findings-sync.md, sonar/issues.py, sonar/syncer.py, test/unit/test_users.py
=> Fixes #1873

cli/findings_export.py, sonar/branches.py, sonar/components.py, sonar/config.json, sonar/config.py, sonar/issues.py, test/unit/test_findings.py
=> Filters on issue status

sonar/rules.py
=> Fixes #1960
